version: '3.8'

services:
  backend:
    build:
      context: ./abnormalsecurity-backend-master
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./abnormalsecurity-backend-master:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=secure_file.settings
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secure_file
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: 